Controllers/CandidateReqsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobShop;

namespace JobShop.Controllers
{
    public class CandidateReqsController : Controller
    {
        private JobShopEntities db = new JobShopEntities();

        // GET: CandidateReqs
        public async Task<ActionResult> Index()
        {
            var candidateReq = db.CandidateReq.Include(c => c.Candidates);
            return View(await candidateReq.ToListAsync());
        }

        // GET: CandidateReqs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CandidateReq candidateReq = await db.CandidateReq.FindAsync(id);
            if (candidateReq == null)
            {
                return HttpNotFound();
            }
            return View(candidateReq);
        }

        // GET: CandidateReqs/Create
        public ActionResult Create()
        {
            ViewBag.Id_CV = new SelectList(db.Candidates, "IdCV", "User");
            return View();
        }

        // POST: CandidateReqs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IdReq,Id_CV,Requirement")] CandidateReq candidateReq)
        {
            if (ModelState.IsValid)
            {
                db.CandidateReq.Add(candidateReq);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Id_CV = new SelectList(db.Candidates, "IdCV", "User", candidateReq.Id_CV);
            return View(candidateReq);
        }

        // GET: CandidateReqs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CandidateReq candidateReq = await db.CandidateReq.FindAsync(id);
            if (candidateReq == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_CV = new SelectList(db.Candidates, "IdCV", "User", candidateReq.Id_CV);
            return View(candidateReq);
        }

        // POST: CandidateReqs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IdReq,Id_CV,Requirement")] CandidateReq candidateReq)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidateReq).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Id_CV = new SelectList(db.Candidates, "IdCV", "User", candidateReq.Id_CV);
            return View(candidateReq);
        }

        // GET: CandidateReqs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CandidateReq candidateReq = await db.CandidateReq.FindAsync(id);
            if (candidateReq == null)
            {
                return HttpNotFound();
            }
            return View(candidateReq);
        }

        // POST: CandidateReqs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            CandidateReq candidateReq = await db.CandidateReq.FindAsync(id);
            db.CandidateReq.Remove(candidateReq);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using JobShop.Models;

namespace JobShop
{
    public class CandidatesController : Controller
    {
        private JobShopEntities db = new JobShopEntities();

        // GET: Candidates
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //stuff for paging, searching and sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //         
            var candidates = db.Candidates.Include(c => c.AspNetUsers);

            //Some search stuff
            if (!String.IsNullOrEmpty(searchString))
            {
                candidates = candidates.Where(s => s.Titlu.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }
            //
            switch (sortOrder)
            {
                case "name_desc":
                    candidates = candidates.OrderByDescending(s => s.Titlu);
                    break;
                case "Date":
                    candidates = candidates.OrderBy(s => s.DateAdd);
                    break;
                case "date_desc":
                    candidates = candidates.OrderByDescending(s => s.DateAdd);
                    break;
                default:
                    //jobs = jobs.OrderBy(s => s.Titlu);
                    candidates = candidates.OrderBy(s => s.DateAdd);
                    break;
            }
            //
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(candidates.ToPagedList(pageNumber, pageSize));

            //return View(candidates.ToList());
        }

        // GET: Candidates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidates candidates = db.Candidates.Find(id);
            if (candidates == null)
            {
                return HttpNotFound();
            }
            return View(candidates);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCV,User,Experienta,Latitudine,Longitudine,address,ZIP")] Candidates candidates)
        {
            if (ModelState.IsValid)
            {
                db.Candidates.Add(candidates);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", candidates.User);
            return View(candidates);
        }

        // GET: Candidates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidates candidates = db.Candidates.Find(id);
            if (candidates == null)
            {
                return HttpNotFound();
            }
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", candidates.User);
            return View(candidates);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCV,User,Experienta,Latitudine,Longitudine,address,ZIP")] Candidates candidates)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidates).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", candidates.User);
            return View(candidates);
        }

        // GET: Candidates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidates candidates = db.Candidates.Find(id);
            if (candidates == null)
            {
                return HttpNotFound();
            }
            return View(candidates);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidates candidates = db.Candidates.Find(id);
            db.Candidates.Remove(candidates);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using JobShop.Models;

namespace JobShop
{
    public class JobsController : Controller
    {
        private JobShopEntities db = new JobShopEntities();

        // GET: Jobs
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //stuff for paging, searching and sorting
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            //
            var jobs = db.Jobs.Include(j => j.AspNetUsers);
            //Some search stuff
            if (!String.IsNullOrEmpty(searchString))
            {
                jobs = jobs.Where(s => s.Titlu.Contains(searchString)
                                       || s.Description.Contains(searchString));
            }
            //
            switch (sortOrder)
            {
                case "name_desc":
                    jobs = jobs.OrderByDescending(s => s.Titlu);
                    break;
                case "Date":
                    jobs = jobs.OrderBy(s => s.DateAdd);
                    break;
                case "date_desc":
                    jobs = jobs.OrderByDescending(s => s.DateAdd);
                    break;
                default:
                    //jobs = jobs.OrderBy(s => s.Titlu);
                    jobs = jobs.OrderBy(s => s.DateAdd);
                    break; 
            }
            //
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(jobs.ToPagedList(pageNumber, pageSize));
            //return View(jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobs jobs = db.Jobs.Find(id);
            if (jobs == null)
            {
                return HttpNotFound();
            }
            return View(jobs);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdJob,IdWho,User,DateAdd,ImageSRC,Titlu,WhereWhat,Description,Content,Solicitare,DateStart,DateEnd,Orar,Address,Latitudine,Longitudine,ZIP")] Jobs jobs)
        {
            if (ModelState.IsValid)
            {
                db.Jobs.Add(jobs);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", jobs.User);
            return View(jobs);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobs jobs = db.Jobs.Find(id);
            if (jobs == null)
            {
                return HttpNotFound();
            }
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", jobs.User);
            return View(jobs);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdJob,IdWho,User,DateAdd,ImageSRC,Titlu,WhereWhat,Description,Content,Solicitare,DateStart,DateEnd,Orar,Address,Latitudine,Longitudine,ZIP")] Jobs jobs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.User = new SelectList(db.AspNetUsers, "Id", "Email", jobs.User);
            return View(jobs);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobs jobs = db.Jobs.Find(id);
            if (jobs == null)
            {
                return HttpNotFound();
            }
            return View(jobs);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jobs jobs = db.Jobs.Find(id);
            db.Jobs.Remove(jobs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_HeaderBanner.cshtml
<div class="header-banner">
    <div class="container">
        <div class="row">
            <!--Here comes the jobs view-->
            @*Latest Jobs*@
            
                        @*
                    @Html.Partial("~/Views/Shared/LatestJobs.cshtml", new JobShop.Models.HomePageModel())
                @Html.Partial("ViewJobs")
                    @Html.Partial("~/Views/ViewJobs/Index.cshtml")
                    @Html.Partial("~/Views/ViewJobs/Index.cshtml", new JobShop.Jobs { IdJob = Model.IdJob })
                    @Html.Partial("~/Views/Shared/LatestJobs.cshtml", new JobShop.Jobs { IdJob = Model.IdJob })
        @Html.Partial("~/Views/Shared/LatestJobs.cshtml")
                        *@
            
            <!--Here comes the candidates view-->
            @*Latest Candidates*@
            
                                    @*
        @Html.Partial("~/Views/Shared/LatestCandidates.cshtml", new JobShop.Models.HomePageModel())
                @Html.Partial("ViewCandidates")
                @Html.Partial("~/Views/ViewCandidates/Index.cshtml")
                @Html.Partial("~/Views/ViewCandidates/Index.cshtml", new JobShop.Candidates { IdCV = Model.IdCV })
                @Html.Partial("~/Views/Shared/LatestCandidates.cshtml", new JobShop.Candidates { IdCV = Model.IdCV })
                    @Html.Partial("~/Views/Shared/LatestCandidates.cshtml")
                                    *@
        </div>
    </div>
</div>

Views/Shared/_HeaderPageTitle.cshtml
<div class="header-page-title">
    
    <div class="container">
        <h3>@ViewBag.Title</h3>
    </div>
</div>

Views/Shared/_Navigation.cshtml
<!-- Mobile Menu Toggle -->
<a id="mobile-menu-toggle" href="#"><span></span></a>
<!-- Primary Nav -->
<nav>
    <ul class="primary-nav">
        <li class="active">
            <!--was with has-submenu-->
            @Html.ActionLink("Home", "Index", "Home")
            @*<ul>
                    <li><a href="default.apsx">Home with Boxes</a></li>
                    <li><a href="homepage-slider.html">Home with Slider</a></li>
                </ul>
                <span class="submenu-arrow"></span>*@
        </li>
        <li class="has-submenu">
            @Html.ActionLink("Joburi", "Index", "Jobs")
            <ul>
                <li>@Html.ActionLink("Job Detail", "Index", "JobDetail")</li>
                <li>@Html.ActionLink("Skills", "Index", "JobsSkills")</li>
                <li>@Html.ActionLink("Requirements", "Index", "JobsRequirements")</li>
            </ul>
            <span class="submenu-arrow"></span>
        </li>
        <li class="has-submenu">
            @Html.ActionLink("Candidati", "Index", "Candidates")
            <ul>
                <li>@Html.ActionLink("Candidate Detail", "Details", "Candidates")</li>
                <li>@Html.ActionLink("Skills", "Index", "CandidateSkills")</li>
                <li>@Html.ActionLink("Requirements", "Index", "CandidateReqs")</li>
                <li>@Html.ActionLink("Experience", "Index", "CandidateExperiences")</li>
                <li>@Html.ActionLink("Education", "Index", "CandidateEducations")</li>
                <li><a href="candidates.html">Listing</a></li>
                <li><a href="candidates-sidebar.html">Listing cu Sidebar</a></li>
                <li><a href="candidate-details.html">Detalii</a></li>
            </ul>
            <span class="submenu-arrow"></span>
        </li>
        <li class="has-submenu">
            @Html.ActionLink("Despre Noi", "About", "Home")
            <ul>
                <li><a href="partners.html">Partneri</a></li>
                <li><a href="contact-us.html">Contacti-ne</a></li>
            </ul>
            <span class="submenu-arrow"></span>
        </li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
        <li>@Html.ActionLink("Inregistrare", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
        @*<li><a href="~/Views/Shared/Register.cshtml">Inregistrare</a></li>*@
    </ul>
</nav>